#!/bin/sh

if command -v dosbox-x >/dev/null 2>&1; then
    source_file="$1"
    obj_file="${source_file%.c}.obj"
    dosbox-x -nolog -fastlaunch -c "H:" -c "C:\WATCOM\BINW\WCC -4 -d3 -s -wx -ms -zl -za99 -fo=BUILD\STAGE2\C\\$obj_file SRC\BOOTLO~1\STAGE2\\$source_file" -c "exit"
else
    echo "dosbox-x not found"
    exit 1
fi
